### ISSUE TITLE
exports is not defined when importing from ESM

### ISSUE THREAD

**Issue by btakita** [cotag/ts-md5#32]
Getting the `exports is not defined` error. Please add support for ESM imports.

**Comment by btakita** [comment]
Strange, now it works. I used to have `import 'ts-md5/src/md5'`. After switching to `import 'ts-md5'` it works.

**Comment by btakita** [comment]
Actually it's still happening. I'm using vite.

```
1:31:43 AM [vite] ✨ dependencies updated, reloading page...
1:31:43 AM [vite] new dependencies found: @ctx-core/array, @ctx-core/event-log, fast-deep-equal/es6, updating...
1:31:43 AM [vite] Error when evaluating SSR module /@fs/home/user/work/project/node_modules/.pnpm/ts-md5@1.2.9/node_modules/ts-md5/dist/md5.js:
ReferenceError: exports is not defined
    at eval (/@fs/home/user/work/project/node_modules/.pnpm/ts-md5@1.2.9/node_modules/ts-md5/dist/md5.js:56:23)
    at instantiateModule (/home/user/work/project/node_modules/.pnpm/vite@2.4.2/node_modules/vite/dist/node/chunks/dep-11db14da.js:73323:166)
```

**Comment by MrYuion** [comment]
ES Modules have be added as of v1.3.0
